version: "3.4"
services:
  db:
    container_name: "zdl_wordprofile_db"
    image: mysql:5
    command:
      "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    environment:
      MYSQL_DATABASE: "wp"
      MYSQL_USER: "wp"
      MYSQL_PASSWORD: "wp"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    name: "zdl_wordprofile_db"
