services:
  db:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: "wp"
      MYSQL_USER: "wp"
      MYSQL_PASSWORD: "wp"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    user: ${USER_GROUP}
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  api:
    image: docker-registry.zdl.org/zdl-wordprofile/api
    build:
      context: .
    environment:
      WP_DB_HOST: "db"
    ports:
      - "8086:8086"

volumes:
  db:
